### ISSUE TITLE
Consider removing default throttling or create a command to "clear" throttling 

### ISSUE THREAD

**Issue by Borets** [saucelabs/speedo#47] opened 2019-05-01 01:41 UTC
After seeing multiple customers struggle to understand why after running speedo run the page load times of their pages were way higher than expected we need to either clarify it or remove it. After looking at the lighthouse examples I noticed that even though they have throtelling enabled by default they also run tests with a mobile profile (Moto 5x) so it makes a bit more sense to the user why the page load is running under throttled CPU. 

So in order to clear the confusion, I believe we have several options: 

Option 1. Remove throttling altogether from the default settings
Option 2. Make it very clear in the UI and speedo logs that the test is running with specific throttling settings
- If we decide to go with #2 we need to give users a clear command to clear the settings rather than asking them to do what 

Option 3. Define two very clear profiles (mobile & desktop) and allow users to select how they would like to run the performance tests. One will have throtelling and mobile device size enabled the other type won't

**Comment by christian-bromann** [comment] 2019-05-06 19:08
> Option 2. Make it very clear in the UI and speedo logs that the test is running with specific throttling settings

We should do that and add the profile (CPU/Network throttling) to the job name. Again, the throttling is only being used in order to help us finding performance regressions in the data.

**Comment by christian-bromann** [comment] 2019-05-06 19:09
Duplicate of #46

**Closed by christian-bromann** 2019-05-06 19:09 UTC
