### ISSUE TITLE
Update the -help parameter to reflect the latest changes with CPU & Network Throttling

### ISSUE THREAD

**Issue by Borets** [saucelabs/speedo#40] opened 2019-04-22 01:28 UTC
With the latest release of speedo, we have added an option to change the CPU and Network Throttling but we haven't actually reflected the commands in the --help output. 
Let's update the help command with the newly added configuration as well as make really clear what are the defaults around these two settings

**Comment by christian-bromann** [comment] 2019-04-23 21:49
duplicate of #41

**Closed by christian-bromann** 2019-04-23 21:49 UTC
